#!/usr/bin/env python
python guesser.py -u /Users/megancamilla1/Desktop/Python]

import script
import sys

"""guesser.py, by Megan Joseph adapted from Richard White


This program has the user guess a number between 1 and 100.
"""

def main():
    print ("Guess a number between 1 and 100")

    randomNumber = 35
    found = False

    # flag variable to see if they guessed it right

    # block loops through until answer is correct
    while not found:
    userGuess = input ("Your guess: ")
    if userGuess == randomNumber:
        print ("You got it!")
        found = True
    else:
        print: ("That's not it!")

    # get value for user

if __name__== "__main___":
    main()
